# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ElectronicBill_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(321, 306)
        self.state_btn = QtWidgets.QPushButton(Form)
        self.state_btn.setGeometry(QtCore.QRect(180, 90, 61, 31))
        self.state_btn.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.state_btn.setObjectName("state_btn")
        self.TRADING_NUM_LE = QtWidgets.QLineEdit(Form)
        self.TRADING_NUM_LE.setGeometry(QtCore.QRect(60, 30, 61, 31))
        self.TRADING_NUM_LE.setObjectName("TRADING_NUM_LE")
        self.MARKET_LE = QtWidgets.QLineEdit(Form)
        self.MARKET_LE.setGeometry(QtCore.QRect(0, 0, 61, 31))
        self.MARKET_LE.setObjectName("MARKET_LE")
        self.ORDER_SIZE_LE = QtWidgets.QLineEdit(Form)
        self.ORDER_SIZE_LE.setGeometry(QtCore.QRect(240, 60, 61, 31))
        self.ORDER_SIZE_LE.setObjectName("ORDER_SIZE_LE")
        self.TRADING_LE = QtWidgets.QLineEdit(Form)
        self.TRADING_LE.setGeometry(QtCore.QRect(60, 0, 61, 31))
        self.TRADING_LE.setObjectName("TRADING_LE")
        self.m_low_btn = QtWidgets.QPushButton(Form)
        self.m_low_btn.setGeometry(QtCore.QRect(120, 0, 31, 31))
        self.m_low_btn.setObjectName("m_low_btn")
        self.updata_btn = QtWidgets.QPushButton(Form)
        self.updata_btn.setGeometry(QtCore.QRect(120, 90, 61, 31))
        self.updata_btn.setStyleSheet("")
        self.updata_btn.setObjectName("updata_btn")
        self.p_low_btn = QtWidgets.QPushButton(Form)
        self.p_low_btn.setGeometry(QtCore.QRect(120, 30, 31, 31))
        self.p_low_btn.setObjectName("p_low_btn")
        self.p_add_btn = QtWidgets.QPushButton(Form)
        self.p_add_btn.setGeometry(QtCore.QRect(210, 30, 31, 31))
        self.p_add_btn.setObjectName("p_add_btn")
        self.P_PER_LE = QtWidgets.QLineEdit(Form)
        self.P_PER_LE.setGeometry(QtCore.QRect(150, 30, 61, 31))
        self.P_PER_LE.setObjectName("P_PER_LE")
        self.T_PRICE_LE = QtWidgets.QLineEdit(Form)
        self.T_PRICE_LE.setGeometry(QtCore.QRect(150, 60, 61, 31))
        self.T_PRICE_LE.setObjectName("T_PRICE_LE")
        self.t_low_btn = QtWidgets.QPushButton(Form)
        self.t_low_btn.setGeometry(QtCore.QRect(120, 60, 31, 31))
        self.t_low_btn.setObjectName("t_low_btn")
        self.t_add_btn = QtWidgets.QPushButton(Form)
        self.t_add_btn.setGeometry(QtCore.QRect(210, 60, 31, 31))
        self.t_add_btn.setObjectName("t_add_btn")
        self.t_low_2_btn = QtWidgets.QPushButton(Form)
        self.t_low_2_btn.setGeometry(QtCore.QRect(120, 180, 31, 31))
        self.t_low_2_btn.setObjectName("t_low_2_btn")
        self.P_PER_2_LE = QtWidgets.QLineEdit(Form)
        self.P_PER_2_LE.setGeometry(QtCore.QRect(150, 150, 61, 31))
        self.P_PER_2_LE.setObjectName("P_PER_2_LE")
        self.T_PRICE_2_LE = QtWidgets.QLineEdit(Form)
        self.T_PRICE_2_LE.setGeometry(QtCore.QRect(150, 180, 61, 31))
        self.T_PRICE_2_LE.setObjectName("T_PRICE_2_LE")
        self.t_add_2_btn = QtWidgets.QPushButton(Form)
        self.t_add_2_btn.setGeometry(QtCore.QRect(210, 180, 31, 31))
        self.t_add_2_btn.setObjectName("t_add_2_btn")
        self.state_2_btn = QtWidgets.QPushButton(Form)
        self.state_2_btn.setGeometry(QtCore.QRect(180, 210, 61, 31))
        self.state_2_btn.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.state_2_btn.setObjectName("state_2_btn")
        self.updata_2_btn = QtWidgets.QPushButton(Form)
        self.updata_2_btn.setGeometry(QtCore.QRect(120, 210, 61, 31))
        self.updata_2_btn.setStyleSheet("")
        self.updata_2_btn.setObjectName("updata_2_btn")
        self.m_low_2_btn = QtWidgets.QPushButton(Form)
        self.m_low_2_btn.setGeometry(QtCore.QRect(120, 120, 31, 31))
        self.m_low_2_btn.setObjectName("m_low_2_btn")
        self.p_low_2_btn = QtWidgets.QPushButton(Form)
        self.p_low_2_btn.setGeometry(QtCore.QRect(120, 150, 31, 31))
        self.p_low_2_btn.setObjectName("p_low_2_btn")
        self.m_add_2_btn = QtWidgets.QPushButton(Form)
        self.m_add_2_btn.setGeometry(QtCore.QRect(210, 120, 31, 31))
        self.m_add_2_btn.setObjectName("m_add_2_btn")
        self.p_add_2_btn = QtWidgets.QPushButton(Form)
        self.p_add_2_btn.setGeometry(QtCore.QRect(210, 150, 31, 31))
        self.p_add_2_btn.setObjectName("p_add_2_btn")
        self.M_PRICE_2_LE = QtWidgets.QLineEdit(Form)
        self.M_PRICE_2_LE.setGeometry(QtCore.QRect(150, 120, 61, 31))
        self.M_PRICE_2_LE.setObjectName("M_PRICE_2_LE")
        self.listView = QtWidgets.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(0, 60, 121, 181))
        self.listView.setObjectName("listView")
        self.m_add_btn = QtWidgets.QPushButton(Form)
        self.m_add_btn.setGeometry(QtCore.QRect(210, 0, 31, 31))
        self.m_add_btn.setObjectName("m_add_btn")
        self.M_PRICE_LE = QtWidgets.QLineEdit(Form)
        self.M_PRICE_LE.setGeometry(QtCore.QRect(150, 0, 61, 31))
        self.M_PRICE_LE.setObjectName("M_PRICE_LE")
        self.MARKET_SMALL_WRT_RATIO_LE = QtWidgets.QLineEdit(Form)
        self.MARKET_SMALL_WRT_RATIO_LE.setGeometry(QtCore.QRect(240, 0, 61, 31))
        self.MARKET_SMALL_WRT_RATIO_LE.setObjectName("MARKET_SMALL_WRT_RATIO_LE")
        self.WRT_RATIO_LE = QtWidgets.QLineEdit(Form)
        self.WRT_RATIO_LE.setGeometry(QtCore.QRect(240, 30, 61, 31))
        self.WRT_RATIO_LE.setObjectName("WRT_RATIO_LE")
        self.Submit_btn = QtWidgets.QPushButton(Form)
        self.Submit_btn.setGeometry(QtCore.QRect(0, 240, 61, 31))
        self.Submit_btn.setStyleSheet("")
        self.Submit_btn.setObjectName("Submit_btn")
        self.Reset_btn = QtWidgets.QPushButton(Form)
        self.Reset_btn.setGeometry(QtCore.QRect(60, 240, 61, 31))
        self.Reset_btn.setStyleSheet("")
        self.Reset_btn.setObjectName("Reset_btn")
        self.PASS_WORD_LE = QtWidgets.QLineEdit(Form)
        self.PASS_WORD_LE.setGeometry(QtCore.QRect(0, 30, 61, 31))
        self.PASS_WORD_LE.setObjectName("PASS_WORD_LE")

        self.retranslateUi(Form)
        self.m_low_btn.clicked.connect(Form.m_price_pane) # type: ignore
        self.m_add_btn.clicked.connect(Form.m_price_pane) # type: ignore
        self.p_low_btn.clicked.connect(Form.p_per_pane) # type: ignore
        self.p_add_btn.clicked.connect(Form.p_per_pane) # type: ignore
        self.t_low_btn.clicked.connect(Form.t_price_pane) # type: ignore
        self.t_add_btn.clicked.connect(Form.t_price_pane) # type: ignore
        self.updata_btn.clicked.connect(Form.updata_pane) # type: ignore
        self.state_btn.clicked['bool'].connect(Form.buy_pane) # type: ignore
        self.m_low_2_btn.clicked.connect(Form.m_price_2_pane) # type: ignore
        self.m_add_2_btn.clicked.connect(Form.m_price_2_pane) # type: ignore
        self.p_low_2_btn.clicked.connect(Form.p_per_2_pane) # type: ignore
        self.p_add_2_btn.clicked.connect(Form.p_per_2_pane) # type: ignore
        self.t_low_2_btn.clicked.connect(Form.t_price_2_pane) # type: ignore
        self.t_add_2_btn.clicked.connect(Form.t_price_2_pane) # type: ignore
        self.updata_2_btn.clicked.connect(Form.updata_2_pane) # type: ignore
        self.state_2_btn.clicked['bool'].connect(Form.sell_pane) # type: ignore
        self.Submit_btn.clicked.connect(Form.subimit) # type: ignore
        self.Reset_btn.clicked.connect(Form.reset_pane) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.state_btn.setText(_translate("Form", "买"))
        self.TRADING_NUM_LE.setText(_translate("Form", "经纪号"))
        self.MARKET_LE.setText(_translate("Form", "行情代码"))
        self.ORDER_SIZE_LE.setText(_translate("Form", "仓位"))
        self.TRADING_LE.setText(_translate("Form", "交易代码"))
        self.m_low_btn.setText(_translate("Form", "-"))
        self.updata_btn.setText(_translate("Form", "更新"))
        self.p_low_btn.setText(_translate("Form", "-"))
        self.p_add_btn.setText(_translate("Form", "+"))
        self.P_PER_LE.setText(_translate("Form", "百分比"))
        self.T_PRICE_LE.setText(_translate("Form", "交易价格"))
        self.t_low_btn.setText(_translate("Form", "-"))
        self.t_add_btn.setText(_translate("Form", "+"))
        self.t_low_2_btn.setText(_translate("Form", "-"))
        self.P_PER_2_LE.setText(_translate("Form", "百分比"))
        self.T_PRICE_2_LE.setText(_translate("Form", "交易价格"))
        self.t_add_2_btn.setText(_translate("Form", "+"))
        self.state_2_btn.setText(_translate("Form", "卖"))
        self.updata_2_btn.setText(_translate("Form", "更新"))
        self.m_low_2_btn.setText(_translate("Form", "-"))
        self.p_low_2_btn.setText(_translate("Form", "-"))
        self.m_add_2_btn.setText(_translate("Form", "+"))
        self.p_add_2_btn.setText(_translate("Form", "+"))
        self.M_PRICE_2_LE.setText(_translate("Form", "行情价格"))
        self.m_add_btn.setText(_translate("Form", "+"))
        self.M_PRICE_LE.setText(_translate("Form", "行情价格"))
        self.MARKET_SMALL_WRT_RATIO_LE.setText(_translate("Form", "最小变动"))
        self.WRT_RATIO_LE.setText(_translate("Form", "波动率"))
        self.Submit_btn.setText(_translate("Form", "提交"))
        self.Reset_btn.setText(_translate("Form", "重置"))
        self.PASS_WORD_LE.setText(_translate("Form", "密码"))
