# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MonitorTickerHandler_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(246, 243)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 241, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.listView = QtWidgets.QListView(self.layoutWidget)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 0, 6, 2)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.DEFAULTAMPLITUDE_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.DEFAULTAMPLITUDE_LE.setClearButtonEnabled(True)
        self.DEFAULTAMPLITUDE_LE.setObjectName("DEFAULTAMPLITUDE_LE")
        self.gridLayout.addWidget(self.DEFAULTAMPLITUDE_LE, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 2)
        self.DEFAULTTURNOVER_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.DEFAULTTURNOVER_LE.setClearButtonEnabled(True)
        self.DEFAULTTURNOVER_LE.setObjectName("DEFAULTTURNOVER_LE")
        self.gridLayout.addWidget(self.DEFAULTTURNOVER_LE, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.SUMTURNOVER_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.SUMTURNOVER_LE.setClearButtonEnabled(True)
        self.SUMTURNOVER_LE.setObjectName("SUMTURNOVER_LE")
        self.gridLayout.addWidget(self.SUMTURNOVER_LE, 2, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 2, 1, 1)
        self.MARKET_SECURITY_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.MARKET_SECURITY_LE.setClearButtonEnabled(True)
        self.MARKET_SECURITY_LE.setObjectName("MARKET_SECURITY_LE")
        self.gridLayout.addWidget(self.MARKET_SECURITY_LE, 3, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 2, 1, 1)
        self.DEFAULTMULTIPLE_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.DEFAULTMULTIPLE_LE.setClearButtonEnabled(True)
        self.DEFAULTMULTIPLE_LE.setObjectName("DEFAULTMULTIPLE_LE")
        self.gridLayout.addWidget(self.DEFAULTMULTIPLE_LE, 4, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 2, 1, 1)
        self.LIFECYCLE_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.LIFECYCLE_LE.setClearButtonEnabled(True)
        self.LIFECYCLE_LE.setObjectName("LIFECYCLE_LE")
        self.gridLayout.addWidget(self.LIFECYCLE_LE, 5, 4, 1, 1)
        self.Exit_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Exit_btn.setObjectName("Exit_btn")
        self.gridLayout.addWidget(self.Exit_btn, 6, 0, 1, 1)
        self.Submit_btn_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.Submit_btn_2.setEnabled(True)
        self.Submit_btn_2.setStyleSheet("")
        self.Submit_btn_2.setObjectName("Submit_btn_2")
        self.gridLayout.addWidget(self.Submit_btn_2, 6, 1, 1, 2)
        self.Submit_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Submit_btn.setEnabled(False)
        self.Submit_btn.setStyleSheet("")
        self.Submit_btn.setObjectName("Submit_btn")
        self.gridLayout.addWidget(self.Submit_btn, 6, 3, 1, 2)

        self.retranslateUi(Form)
        self.Submit_btn.clicked.connect(Form.subimit) # type: ignore
        self.MARKET_SECURITY_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.DEFAULTAMPLITUDE_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.DEFAULTMULTIPLE_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.DEFAULTTURNOVER_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.LIFECYCLE_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.SUMTURNOVER_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.Exit_btn.clicked.connect(Form.exit_pane) # type: ignore
        self.Submit_btn_2.clicked.connect(Form.stop_btn) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "预设振幅"))
        self.DEFAULTAMPLITUDE_LE.setText(_translate("Form", "6"))
        self.label_3.setText(_translate("Form", "预设成交额"))
        self.DEFAULTTURNOVER_LE.setText(_translate("Form", "25000"))
        self.label_4.setText(_translate("Form", "同向倍数"))
        self.SUMTURNOVER_LE.setText(_translate("Form", "10"))
        self.label_6.setText(_translate("Form", "监测地址"))
        self.MARKET_SECURITY_LE.setText(_translate("Form", "C:/Users/MR.jiang/Desktop/12.csv"))
        self.label_2.setText(_translate("Form", "预设倍数"))
        self.DEFAULTMULTIPLE_LE.setText(_translate("Form", "30"))
        self.label_5.setText(_translate("Form", "生命周期"))
        self.LIFECYCLE_LE.setText(_translate("Form", "10"))
        self.Exit_btn.setText(_translate("Form", "退出"))
        self.Submit_btn_2.setText(_translate("Form", "暂停"))
        self.Submit_btn.setText(_translate("Form", "提交"))
