# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GetsJumpPoint_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(206, 229)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 1, 202, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.listView = QtWidgets.QListView(self.layoutWidget)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.MARKET_SECURITY_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.MARKET_SECURITY_LE.setClearButtonEnabled(True)
        self.MARKET_SECURITY_LE.setObjectName("MARKET_SECURITY_LE")
        self.gridLayout.addWidget(self.MARKET_SECURITY_LE, 1, 1, 1, 1)
        self.Submit_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Submit_btn.setEnabled(False)
        self.Submit_btn.setStyleSheet("")
        self.Submit_btn.setObjectName("Submit_btn")
        self.gridLayout.addWidget(self.Submit_btn, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.TRADING_SECURITY_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.TRADING_SECURITY_LE.setClearButtonEnabled(True)
        self.TRADING_SECURITY_LE.setObjectName("TRADING_SECURITY_LE")
        self.gridLayout.addWidget(self.TRADING_SECURITY_LE, 2, 1, 1, 1)
        self.Stop_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Stop_btn.setStyleSheet("")
        self.Stop_btn.setObjectName("Stop_btn")
        self.gridLayout.addWidget(self.Stop_btn, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.TRADING_NUM_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.TRADING_NUM_LE.setClearButtonEnabled(True)
        self.TRADING_NUM_LE.setObjectName("TRADING_NUM_LE")
        self.gridLayout.addWidget(self.TRADING_NUM_LE, 3, 1, 1, 1)
        self.Exit_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Exit_btn.setStyleSheet("")
        self.Exit_btn.setObjectName("Exit_btn")
        self.gridLayout.addWidget(self.Exit_btn, 3, 2, 1, 1)

        self.retranslateUi(Form)
        self.TRADING_NUM_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.TRADING_SECURITY_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.MARKET_SECURITY_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.Exit_btn.clicked.connect(Form.exit_pane) # type: ignore
        self.Submit_btn.clicked.connect(Form.subimit) # type: ignore
        self.Stop_btn.clicked.connect(Form.stop_pane) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "行情代码"))
        self.MARKET_SECURITY_LE.setText(_translate("Form", "HK.16976"))
        self.Submit_btn.setText(_translate("Form", "提交"))
        self.label_2.setText(_translate("Form", "交易代码"))
        self.TRADING_SECURITY_LE.setText(_translate("Form", "350000"))
        self.Stop_btn.setText(_translate("Form", "清除"))
        self.label_5.setText(_translate("Form", " 经纪号"))
        self.TRADING_NUM_LE.setText(_translate("Form", "SELL"))
        self.Exit_btn.setText(_translate("Form", "退出"))
