# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TransactionWindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(325, 465)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(6, 6, 151, 261))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.listView = QtWidgets.QListView(self.widget)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 0, 6, 2)
        self.PRICE_LE = QtWidgets.QLineEdit(self.widget)
        self.PRICE_LE.setClearButtonEnabled(True)
        self.PRICE_LE.setObjectName("PRICE_LE")
        self.gridLayout.addWidget(self.PRICE_LE, 0, 2, 1, 1)
        self.VOLUME_LE = QtWidgets.QLineEdit(self.widget)
        self.VOLUME_LE.setClearButtonEnabled(True)
        self.VOLUME_LE.setObjectName("VOLUME_LE")
        self.gridLayout.addWidget(self.VOLUME_LE, 1, 2, 1, 1)
        self.MARKET_PRICE_LE = QtWidgets.QLineEdit(self.widget)
        self.MARKET_PRICE_LE.setObjectName("MARKET_PRICE_LE")
        self.gridLayout.addWidget(self.MARKET_PRICE_LE, 2, 2, 1, 1)
        self.PERCENT_LE = QtWidgets.QLineEdit(self.widget)
        self.PERCENT_LE.setObjectName("PERCENT_LE")
        self.gridLayout.addWidget(self.PERCENT_LE, 3, 2, 1, 1)
        self.Buy_btn = QtWidgets.QPushButton(self.widget)
        self.Buy_btn.setEnabled(False)
        self.Buy_btn.setStyleSheet("")
        self.Buy_btn.setObjectName("Buy_btn")
        self.gridLayout.addWidget(self.Buy_btn, 4, 2, 1, 1)
        self.Sell_btn = QtWidgets.QPushButton(self.widget)
        self.Sell_btn.setEnabled(False)
        self.Sell_btn.setStyleSheet("")
        self.Sell_btn.setObjectName("Sell_btn")
        self.gridLayout.addWidget(self.Sell_btn, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.MARKET_SECURITY_LE = QtWidgets.QLineEdit(self.widget)
        self.MARKET_SECURITY_LE.setClearButtonEnabled(True)
        self.MARKET_SECURITY_LE.setObjectName("MARKET_SECURITY_LE")
        self.gridLayout.addWidget(self.MARKET_SECURITY_LE, 6, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 0, 1, 1)
        self.TRADING_SECURITY_LE = QtWidgets.QLineEdit(self.widget)
        self.TRADING_SECURITY_LE.setClearButtonEnabled(True)
        self.TRADING_SECURITY_LE.setObjectName("TRADING_SECURITY_LE")
        self.gridLayout.addWidget(self.TRADING_SECURITY_LE, 7, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.TRADING_NUM_LE = QtWidgets.QLineEdit(self.widget)
        self.TRADING_NUM_LE.setClearButtonEnabled(True)
        self.TRADING_NUM_LE.setObjectName("TRADING_NUM_LE")
        self.gridLayout.addWidget(self.TRADING_NUM_LE, 8, 2, 1, 1)
        self.Submit_btn = QtWidgets.QPushButton(self.widget)
        self.Submit_btn.setEnabled(False)
        self.Submit_btn.setStyleSheet("")
        self.Submit_btn.setObjectName("Submit_btn")
        self.gridLayout.addWidget(self.Submit_btn, 9, 0, 1, 1)
        self.Exit_btn = QtWidgets.QPushButton(self.widget)
        self.Exit_btn.setStyleSheet("")
        self.Exit_btn.setObjectName("Exit_btn")
        self.gridLayout.addWidget(self.Exit_btn, 9, 1, 1, 2)

        self.retranslateUi(Form)
        self.TRADING_NUM_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.TRADING_SECURITY_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.MARKET_SECURITY_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.Exit_btn.clicked.connect(Form.exit_pane) # type: ignore
        self.Submit_btn.clicked.connect(Form.subimit) # type: ignore
        self.PRICE_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.VOLUME_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.Buy_btn.clicked.connect(Form.call_btn) # type: ignore
        self.Sell_btn.clicked.connect(Form.sell_btn) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.PRICE_LE.setText(_translate("Form", "买入价格"))
        self.VOLUME_LE.setText(_translate("Form", "成交量"))
        self.MARKET_PRICE_LE.setText(_translate("Form", "市场价"))
        self.PERCENT_LE.setText(_translate("Form", "百分比"))
        self.Buy_btn.setText(_translate("Form", "买入"))
        self.Sell_btn.setText(_translate("Form", "卖出"))
        self.label_6.setText(_translate("Form", "行情代码"))
        self.MARKET_SECURITY_LE.setText(_translate("Form", "HSImain"))
        self.label_2.setText(_translate("Form", "交易代码"))
        self.TRADING_SECURITY_LE.setText(_translate("Form", "65108"))
        self.label_5.setText(_translate("Form", " 经纪号"))
        self.TRADING_NUM_LE.setText(_translate("Form", "9763"))
        self.Submit_btn.setText(_translate("Form", "提交"))
        self.Exit_btn.setText(_translate("Form", "退出"))
