# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AutoFlowTrade_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(293, 443)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 290, 441))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.listView = QtWidgets.QListView(self.layoutWidget)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 0, 1, 8)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.TRADING_SECURITY_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.TRADING_SECURITY_LE.setClearButtonEnabled(True)
        self.TRADING_SECURITY_LE.setObjectName("TRADING_SECURITY_LE")
        self.gridLayout.addWidget(self.TRADING_SECURITY_LE, 1, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 3, 1, 2)
        self.TRADING_NUM_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.TRADING_NUM_LE.setClearButtonEnabled(True)
        self.TRADING_NUM_LE.setObjectName("TRADING_NUM_LE")
        self.gridLayout.addWidget(self.TRADING_NUM_LE, 1, 5, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.MARKET_SECURITY_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.MARKET_SECURITY_LE.setClearButtonEnabled(True)
        self.MARKET_SECURITY_LE.setObjectName("MARKET_SECURITY_LE")
        self.gridLayout.addWidget(self.MARKET_SECURITY_LE, 2, 1, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 3, 1, 2)
        self.MARKET_SMALL_WRT_RATIO_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.MARKET_SMALL_WRT_RATIO_LE.setClearButtonEnabled(True)
        self.MARKET_SMALL_WRT_RATIO_LE.setObjectName("MARKET_SMALL_WRT_RATIO_LE")
        self.gridLayout.addWidget(self.MARKET_SMALL_WRT_RATIO_LE, 2, 5, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.ORDER_SIZE_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.ORDER_SIZE_LE.setClearButtonEnabled(True)
        self.ORDER_SIZE_LE.setObjectName("ORDER_SIZE_LE")
        self.gridLayout.addWidget(self.ORDER_SIZE_LE, 3, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 3, 1, 2)
        self.Reset_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Reset_btn.setStyleSheet("")
        self.Reset_btn.setObjectName("Reset_btn")
        self.gridLayout.addWidget(self.Reset_btn, 4, 0, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 0, 1, 1)
        self.TRIM_PARAGRAPH_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.TRIM_PARAGRAPH_LE.setClearButtonEnabled(True)
        self.TRIM_PARAGRAPH_LE.setObjectName("TRIM_PARAGRAPH_LE")
        self.gridLayout.addWidget(self.TRIM_PARAGRAPH_LE, 3, 5, 1, 3)
        self.Submit_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Submit_btn.setEnabled(False)
        self.Submit_btn.setStyleSheet("")
        self.Submit_btn.setObjectName("Submit_btn")
        self.gridLayout.addWidget(self.Submit_btn, 4, 3, 1, 5)
        self.CALL_PARAGRAPH_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.CALL_PARAGRAPH_LE.setClearButtonEnabled(True)
        self.CALL_PARAGRAPH_LE.setObjectName("CALL_PARAGRAPH_LE")
        self.gridLayout.addWidget(self.CALL_PARAGRAPH_LE, 5, 1, 1, 2)
        self.ORDER_QUANTITY_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.ORDER_QUANTITY_LE.setClearButtonEnabled(True)
        self.ORDER_QUANTITY_LE.setObjectName("ORDER_QUANTITY_LE")
        self.gridLayout.addWidget(self.ORDER_QUANTITY_LE, 6, 1, 1, 2)
        self.PASS_WORD_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.PASS_WORD_LE.setMaxLength(32768)
        self.PASS_WORD_LE.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PASS_WORD_LE.setClearButtonEnabled(True)
        self.PASS_WORD_LE.setObjectName("PASS_WORD_LE")
        self.gridLayout.addWidget(self.PASS_WORD_LE, 7, 1, 1, 2)
        self.Exit_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Exit_btn.setStyleSheet("")
        self.Exit_btn.setObjectName("Exit_btn")
        self.gridLayout.addWidget(self.Exit_btn, 7, 3, 1, 5)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 3, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 6, 3, 1, 2)
        self.PUT_PARAGRAPH_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.PUT_PARAGRAPH_LE.setClearButtonEnabled(True)
        self.PUT_PARAGRAPH_LE.setObjectName("PUT_PARAGRAPH_LE")
        self.gridLayout.addWidget(self.PUT_PARAGRAPH_LE, 5, 5, 1, 3)
        self.OR_CANCEL_ALL_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.OR_CANCEL_ALL_LE.setClearButtonEnabled(True)
        self.OR_CANCEL_ALL_LE.setObjectName("OR_CANCEL_ALL_LE")
        self.gridLayout.addWidget(self.OR_CANCEL_ALL_LE, 6, 5, 1, 3)

        self.retranslateUi(Form)
        self.TRADING_NUM_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.TRADING_SECURITY_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.MARKET_SECURITY_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.Exit_btn.clicked.connect(Form.exit_pane) # type: ignore
        self.Submit_btn.clicked.connect(Form.subimit) # type: ignore
        self.Reset_btn.clicked.connect(Form.reset_pane) # type: ignore
        self.ORDER_SIZE_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.CALL_PARAGRAPH_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.ORDER_QUANTITY_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.PUT_PARAGRAPH_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.MARKET_SMALL_WRT_RATIO_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.PASS_WORD_LE.textEdited['QString'].connect(Form.enable_register_btn) # type: ignore
        self.OR_CANCEL_ALL_LE.textEdited['QString'].connect(Form.enable_register_btn) # type: ignore
        self.TRIM_PARAGRAPH_LE.textEdited['QString'].connect(Form.enable_register_btn) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

        # ▼▼▼ 新增焦点策略设置 ▼▼▼
        # 设置可Tab选中的控件
        self.TRADING_NUM_LE.setFocusPolicy(QtCore.Qt.StrongFocus)  # 经纪号输入框
        self.TRADING_SECURITY_LE.setFocusPolicy(QtCore.Qt.StrongFocus)  # 交易代码输入框
        self.Submit_btn.setFocusPolicy(QtCore.Qt.StrongFocus)  # 提交按钮

        # 禁用其他控件的Tab选中（不影响鼠标操作）
        widgets = [
            self.MARKET_SECURITY_LE, self.MARKET_SMALL_WRT_RATIO_LE,
            self.ORDER_SIZE_LE, self.TRIM_PARAGRAPH_LE, self.CALL_PARAGRAPH_LE,
            self.ORDER_QUANTITY_LE, self.PUT_PARAGRAPH_LE, self.OR_CANCEL_ALL_LE,
            self.PASS_WORD_LE, self.Reset_btn, self.Exit_btn
        ]
        for widget in widgets:
            widget.setFocusPolicy(QtCore.Qt.ClickFocus)  # 保留鼠标交互能力
        # ▲▲▲ 修改结束 ▲▲▲

        self.retranslateUi(Form)
        # ... 后续信号连接代码 ...

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "交易代码"))
        self.TRADING_SECURITY_LE.setText(_translate("Form", "65101"))
        self.label_5.setText(_translate("Form", " 经纪号"))
        self.TRADING_NUM_LE.setText(_translate("Form", "9696"))
        self.label_6.setText(_translate("Form", "行情代码"))
        self.MARKET_SECURITY_LE.setText(_translate("Form", "HSImain"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p align=\"center\">行情最小</p></body></html>"))
        self.MARKET_SMALL_WRT_RATIO_LE.setText(_translate("Form", "1"))
        self.label_7.setText(_translate("Form", "仓位"))
        self.ORDER_SIZE_LE.setText(_translate("Form", "5"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"center\">波动率</p></body></html>"))
        self.Reset_btn.setText(_translate("Form", "重置"))
        self.label_8.setText(_translate("Form", "买入百分比"))
        self.label_9.setText(_translate("Form", "挂单量"))
        self.label_12.setText(_translate("Form", "交易密码"))
        self.TRIM_PARAGRAPH_LE.setText(_translate("Form", "600"))
        self.Submit_btn.setText(_translate("Form", "提交"))
        self.CALL_PARAGRAPH_LE.setText(_translate("Form", "400"))
        self.ORDER_QUANTITY_LE.setText(_translate("Form", "3"))
        self.PASS_WORD_LE.setText(_translate("Form", "111"))
        self.Exit_btn.setText(_translate("Form", "退出"))
        self.label_10.setText(_translate("Form", "卖出百分比"))
        self.label_14.setText(_translate("Form", "是否撤单"))
        self.PUT_PARAGRAPH_LE.setText(_translate("Form", "200"))
        self.OR_CANCEL_ALL_LE.setText(_translate("Form", "0"))
