# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HorizontalAndTop.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(410, 515)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.TRADING_SECURITY_LE = QtWidgets.QLineEdit(Form)
        self.TRADING_SECURITY_LE.setMaximumSize(QtCore.QSize(102, 16777215))
        self.TRADING_SECURITY_LE.setClearButtonEnabled(True)
        self.TRADING_SECURITY_LE.setObjectName("TRADING_SECURITY_LE")
        self.gridLayout.addWidget(self.TRADING_SECURITY_LE, 3, 2, 1, 2)
        self.TRADING_NUM_LE = QtWidgets.QLineEdit(Form)
        self.TRADING_NUM_LE.setMaximumSize(QtCore.QSize(102, 16777215))
        self.TRADING_NUM_LE.setClearButtonEnabled(True)
        self.TRADING_NUM_LE.setObjectName("TRADING_NUM_LE")
        self.gridLayout.addWidget(self.TRADING_NUM_LE, 4, 2, 1, 2)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setMaximumSize(QtCore.QSize(48, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setMaximumSize(QtCore.QSize(48, 16777215))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 2)
        self.Submit_btn = QtWidgets.QPushButton(Form)
        self.Submit_btn.setEnabled(True)
        self.Submit_btn.setMaximumSize(QtCore.QSize(156, 16777215))
        self.Submit_btn.setStyleSheet("")
        self.Submit_btn.setObjectName("Submit_btn")
        self.gridLayout.addWidget(self.Submit_btn, 6, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMaximumSize(QtCore.QSize(48, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 2)
        self.MARKET_SMALL_LE = QtWidgets.QLineEdit(Form)
        self.MARKET_SMALL_LE.setMaximumSize(QtCore.QSize(102, 16777215))
        self.MARKET_SMALL_LE.setClearButtonEnabled(True)
        self.MARKET_SMALL_LE.setObjectName("MARKET_SMALL_LE")
        self.gridLayout.addWidget(self.MARKET_SMALL_LE, 2, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setMaximumSize(QtCore.QSize(48, 16777215))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 2)
        self.listView = QtWidgets.QListView(Form)
        self.listView.setMaximumSize(QtCore.QSize(156, 16777215))
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 0, 1, 4)
        self.Exit_btn = QtWidgets.QPushButton(Form)
        self.Exit_btn.setMaximumSize(QtCore.QSize(75, 16777215))
        self.Exit_btn.setStyleSheet("")
        self.Exit_btn.setObjectName("Exit_btn")
        self.gridLayout.addWidget(self.Exit_btn, 7, 3, 1, 1)
        self.TRADING_SENSITIVITY_LE = QtWidgets.QLineEdit(Form)
        self.TRADING_SENSITIVITY_LE.setMaximumSize(QtCore.QSize(102, 16777215))
        self.TRADING_SENSITIVITY_LE.setClearButtonEnabled(True)
        self.TRADING_SENSITIVITY_LE.setObjectName("TRADING_SENSITIVITY_LE")
        self.gridLayout.addWidget(self.TRADING_SENSITIVITY_LE, 5, 2, 1, 2)
        self.MARKET_SECURITY_LE = QtWidgets.QLineEdit(Form)
        self.MARKET_SECURITY_LE.setMaximumSize(QtCore.QSize(102, 16777215))
        self.MARKET_SECURITY_LE.setClearButtonEnabled(True)
        self.MARKET_SECURITY_LE.setObjectName("MARKET_SECURITY_LE")
        self.gridLayout.addWidget(self.MARKET_SECURITY_LE, 1, 2, 1, 2)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMaximumSize(QtCore.QSize(48, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 2)
        self.Stop_btn = QtWidgets.QPushButton(Form)
        self.Stop_btn.setMaximumSize(QtCore.QSize(75, 16777215))
        self.Stop_btn.setStyleSheet("")
        self.Stop_btn.setObjectName("Stop_btn")
        self.gridLayout.addWidget(self.Stop_btn, 7, 0, 1, 3)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.listView_2 = QtWidgets.QListView(Form)
        self.listView_2.setMinimumSize(QtCore.QSize(226, 495))
        self.listView_2.setObjectName("listView_2")
        self.horizontalLayout_2.addWidget(self.listView_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        self.TRADING_NUM_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.TRADING_SECURITY_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.MARKET_SECURITY_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.Exit_btn.clicked.connect(Form.exit_pane) # type: ignore
        self.Submit_btn.clicked.connect(Form.subimit) # type: ignore
        self.Stop_btn.clicked.connect(Form.stop_pane) # type: ignore
        self.MARKET_SMALL_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        self.TRADING_SENSITIVITY_LE.textChanged['QString'].connect(Form.enable_register_btn) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TRADING_SECURITY_LE.setText(_translate("Form", "65101"))
        self.TRADING_NUM_LE.setText(_translate("Form", "9696"))
        self.label_6.setText(_translate("Form", "行情代码"))
        self.label_8.setText(_translate("Form", "最小变动"))
        self.Submit_btn.setText(_translate("Form", "提交"))
        self.label_2.setText(_translate("Form", "交易代码"))
        self.MARKET_SMALL_LE.setText(_translate("Form", "0.05"))
        self.label_7.setText(_translate("Form", "敏感度"))
        self.Exit_btn.setText(_translate("Form", "退出"))
        self.TRADING_SENSITIVITY_LE.setText(_translate("Form", "9696"))
        self.MARKET_SECURITY_LE.setText(_translate("Form", "HSImain"))
        self.label_5.setText(_translate("Form", "经纪号"))
        self.Stop_btn.setText(_translate("Form", "清除"))
